#!/usr/bin/env sh

set -eu

. ~/.profile

export STTEMP_ASK=$(
	cat <<'EOF'
ask () {
	echo $(dmenu -p "Enter $1" </dev/null)
}
EOF
)


export BODY=$(xclip -o)

xdotool key --clearmodifiers "Ctrl+l"
xdotool key --clearmodifiers "Ctrl+c"
export URL=$(xclip -o -selection primary)
xdotool key --clearmodifiers "Escape"

sttemp webnote >> "$SCRATCH_PATH"
notify-send -t 1500 "Saved to scratch file."
