#!/usr/bin/env sh

set -eu

. ~/.profile

export STTEMP_ASK=$(
	cat <<'EOF'
ask () {
	echo $(dmenu -p "Enter $1" </dev/null)
}
EOF
)


export BODY=$(xclip -o)

xdotool key --clearmodifiers "Ctrl+l"
xdotool key --clearmodifiers "Ctrl+c"
export URL=$(xclip -o -selection primary)
xdotool key --clearmodifiers "Escape"

FILE_NAME=$(date '+%Y-%m-%d-%H%M%S')
sttemp webnote >> "${NOTES_QUEUE}/$FILE_NAME.md"
notify-send -t 1500 "Saved to $FILE_NAME.md"
