.TH STTEMP 1 2021-01-09 V1.0
.SH NAME
sttemp \- simple template manager
.SH SYNOPSIS
.B sttemp
[\fB\-h\fR]

.B sttemp
[\fB\-e\fR]
\fItemplate\fR
[\fIoutput\fR]
.SH DESCRIPTION
.B sttemp
copy file from your template directory and fill all 
substitutions with user input, or environment variables.
Template directory and substitution pattern described in
\fBsrc/config.h\fR file, in suckless style. You can use
\fB~\fR as \fBfirst\fR symbol of your path, for relative
path from your home directory.
.SH OPTIONS
.TP
.BI \-h
displays help information
.TP
.BI \-e
use environment variables for fill substitution in 
template, if \fBsttemp\fR can't find environment variable 
with needed name, it will use user input
.TP
.BI template
name of file in your templates directory, which will use 
to create new file
.TP
.BI output
name of target file, if omit - \fBsttemp\fR will use template name
.SH AUTHOR
Anton Konyahin <\fIme@konyahin.xyz\fR>
